In [1]:
import pandas as pd
from sklearn.feature_extraction import DictVectorizer as DV
import seaborn as sns

In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
abalone = pd.read_csv('abalone.data', 
                   names= ['Sex','Length','Diameter','Height','Whole weight','Shucked weight','Viscera weight','Shell weight','Rings'])
abalone.head()

Sex  Length  Diameter  ...  Viscera weight  Shell weight  Rings
0   M   0.455     0.365  ...          0.1010         0.150     15
1   M   0.350     0.265  ...          0.0485         0.070      7
2   F   0.530     0.420  ...          0.1415         0.210      9
3   M   0.440     0.365  ...          0.1140         0.155     10
4   I   0.330     0.255  ...          0.0395         0.055      7

[5 rows x 9 columns]

In [4]:
encoder = DV(sparse = False)
encoded_sign_abalone = encoder.fit_transform(abalone[['Sex']].T.to_dict().values())
print(encoded_sign_abalone[:10])

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [5]:
abalone = abalone.drop('Sex',1)
abalone_encoded = pd.concat([pd.DataFrame(encoded_sign_abalone,columns=['Female','Infant','Male']),abalone],axis = 1)
abalone_encoded.head()

Female  Infant  Male  ...  Viscera weight  Shell weight  Rings
0     0.0     0.0   1.0  ...          0.1010         0.150     15
1     0.0     0.0   1.0  ...          0.0485         0.070      7
2     1.0     0.0   0.0  ...          0.1415         0.210      9
3     0.0     0.0   1.0  ...          0.1140         0.155     10
4     0.0     1.0   0.0  ...          0.0395         0.055      7

[5 rows x 11 columns]

In [6]:
abalone_encoded.to_csv('abalone_preprocessed.csv')

In [7]:
concrete = pd.read_excel('concrete.xls', names = ['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water','Superplasticizer',
                                                  'Coarse Aggregate', 'Fine Aggregate', 'Age', 'Concrete compressive strength'])
concrete.head()

Cement  Blast Furnace Slag  ...  Age  Concrete compressive strength
0   540.0                 0.0  ...   28                      79.986111
1   540.0                 0.0  ...   28                      61.887366
2   332.5               142.5  ...  270                      40.269535
3   332.5               142.5  ...  365                      41.052780
4   198.6               132.4  ...  360                      44.296075

[5 rows x 9 columns]

In [8]:
concrete.columns

Index(['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'Age',
       'Concrete compressive strength'],
      dtype='object')

In [9]:
concrete.to_csv('concrete_preprocessed.csv')